### ISSUE TITLE
cisco.asa.asa_facts fails to pull object groups (ogs) when object group on the device has 'group-objects' mentioned in it.

### ISSUE THREAD

**Issue by sagarphadatare44** [ansible-collections/cisco.asa#107] opened 2021-04-30 06:26 UTC
##### SUMMARY
When we try to gather object groups from the device using cisco.asa.asa_facts module, it is failing with below error. We observed that on ASA device we have group_objects  are called under some object groups. And mostly this error is stating the same. 

"msg": "Unsupported parameters for (basic.py) module: group_object found in config -> object_groups. Supported parameters include: description, icmp_type, name, network_object, protocol_object, security_group, service_object, user_object",
   

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

 cisco.asa.asa_facts:
    gather_network_resources: ogs

##### ANSIBLE VERSION

```paste below
ansible 2.9.10

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ASA 9.4

##### STEPS TO REPRODUCE

```yaml
      cisco.asa.asa_facts:
        gather_network_resources: ogs
      register: object

```

On asa device, configure object group with group_objects
eg.
# object-group network icmp-type
#group_object ICMP_UNREACHABLE

##### EXPECTED RESULTS

We are expecting all the object group pulled from the device.

##### ACTUAL RESULTS

```paste below
{
    "msg": "Unsupported parameters for (basic.py) module: group_object found in config -> object_groups. Supported parameters include: description, icmp_type, name, network_object, protocol_object, security_group, service_object, user_object",
    "invocation": {
        "module_args": {
            "config": [
                {
                    "object_type": "icmp-type",
                    "object_groups": [
                        {
                            "name": "ICMP",
                            "group_object": "ICMP_UNREACHABLE",
                            "icmp_type": {}
                        },
                        {
                            "name": "ICMP_PING",
                            "icmp_type": {
                                "icmp_object": [
                                    "echo",
                                    "echo-reply"
                                ]
                            }
                        },
                        {
                            "name": "ICMP_TRACEROUTE",
                            "icmp_type": {
                                "icmp_object": [
                                    "time-exceeded",
                                    "traceroute"
                                ]
                            }
                        },
                        {
                            "name": "ICMP_UNREACHABLE",
                            "icmp_type": {
                                "icmp_object": [
                                    "unreachable"
                                ]
                            }
                        }
                    ]
                },
                {
                    "object_type": "network",
                    "object_groups": [
                        {
                            "name": "GRP",
                            "network_object": {}
                        },
                        {
                            "name": "OBJECTGROUPNAME",
                            "description": "PAYROLL \"CUSTOMER\"",
                            "network_object": {
                                "host": [
                                    "192.168.0.200"
                                ]
                            }
                        },
                        {
                            "name": "Object_group_name",
                            "description": "PAYROLL \"Customer\"",
                            "network_object": {
                                "host": [
                                    "192.168.0.200"
                                ]
                            }
                        },
                        {
                            "name": "test_vip_create2",
                            "network_object": {
                                "host": [
                                    "212.68.10.82"
                                ]
                            }
                        }
                    ]
                }
            ],
            "state": "merged",
            "running_config": null
        }
    },
    "_ansible_no_log": false,
    "changed": false,
    "_ansible_delegated_vars": {
        "ansible_host": "172.27.192.40",
        "ansible_port": null,
        "ansible_user": null
    }
}
```

**Comment by justjais** [comment] 2021-04-30 10:57
@sagarphadatare44 Thanks for logging the issue, if feasible can u share the OGs config for triaging the issue.

**Comment by sagarphadatare44** [comment] 2021-04-30 12:37
@justjais 

You can already see the object group configuration in invocation.
But error is mostly because of object group : object_groups": [
                        {
                            "name": "ICMP",
                            "group_object": "ICMP_UNREACHABLE",
                            "icmp_type": {} 
}
Because above object group, 'group_object' is defined and the error is complaining about the same. 

Its very new device and below object groups are configured on the device:

                {
                    "object_type": "icmp-type",
                    "object_groups": [
                        {
                            "name": "ICMP",
                            "group_object": "ICMP_UNREACHABLE",
                            "icmp_type": {}
                        },
                        {
                            "name": "ICMP_PING",
                            "icmp_type": {
                                "icmp_object": [
                                    "echo",
                                    "echo-reply"
                                ]
                            }
                        },
                        {
                            "name": "ICMP_TRACEROUTE",
                            "icmp_type": {
                                "icmp_object": [
                                    "time-exceeded",
                                    "traceroute"
                                ]
                            }
                        },
                        {
                            "name": "ICMP_UNREACHABLE",
                            "icmp_type": {
                                "icmp_object": [
                                    "unreachable"
                                ]
                            }
                        }
                    ]
                },
                {
                    "object_type": "network",
                    "object_groups": [
                        {
                            "name": "GRP",
                            "network_object": {}
                        },
                        {
                            "name": "OBJECTGROUPNAME",
                            "description": "PAYROLL \"CUSTOMER\"",
                            "network_object": {
                                "host": [
                                    "192.168.0.200"
                                ]
                            }
                        },
                        {
                            "name": "Object_group_name",
                            "description": "PAYROLL \"Customer\"",
                            "network_object": {
                                "host": [
                                    "192.168.0.200"
                                ]
                            }
                        },
                        {
                            "name": "test_vip_create2",
                            "network_object": {
                                "host": [
                                    "212.68.10.82"
                                ]
                            }
                        }
                    ]

**Comment by sagarphadatare44** [comment] 2021-05-05 05:34
@justjais, 

Are you able to reproduce this issue? any update on this?

**Comment by phpipam** [comment] 2021-05-11 06:49
Hi, same issue here with group_object, anything I can do to help debugging ?

Ansible version: `ansible 2.10.4`
ASA version: `9.13(1)2` - tested some older releases also

**Comment by phpipam** [comment] 2021-05-11 07:41
Hi @justjais,

here is asa config snippet:
```
object-group network Servers_ext_1
 network-object 172.20.232.0 255.255.254.0

object-group network Servers_ext_2
 network-object 172.20.234.0 255.255.254.0

object-group network Servers_ext
 group-object Servers_ext_1
 group-object Servers_ext_2
```

group-object is causing issue I believe. The problem is I cannot execute any command as it always fails with the same error, I dont need group-objects as such via ansible but they exist in existing configuration.

```yml
TASK [Create object group] ******************************************************************************************************************************************************************************************
fatal: [fw_dc_nms_1]: FAILED! => changed=false
  msg: 'Unsupported parameters for (basic.py) module: group_object found in config -> object_groups. Supported parameters include: description, icmp_type, name, network_object, protocol_object, security_group, service_object, user_object'
```

**Comment by justjais** [comment] 2021-05-14 12:11
@sagarphadatare44 @phpipam Thanks for raising the issue, and yes the issue was indeed happening coz the implementation for `group-object` was missing from `ogs` RM. I've opened a PR to fix the behavior and once merged it'll be queued for the next release. 

Meanwhile, if anyone can confirm that the fix works as expected that'd be great. Thanks

**Closed** 2021-05-17 07:30 UTC
Labels: has_pr

**Comment by phpipam** [comment] 2021-05-17 08:04
Hi @justjais , sorry for late reply.

I just checked and it seems ok so far, I am able to connect to asa.

**Comment by sagarphadatare44** [comment] 2021-05-17 08:55
@justjais, Do you have any tentative date for this version to be released?

**Comment by justjais** [comment] 2021-05-17 09:07
@sagarphadatare44 ASA collection release is planned for today.
