### ISSUE TITLE
Unable to gather facts: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rayterrill** [ansible-collections/cisco.asa#52] opened 2020-06-30 02:44 UTC
##### SUMMARY
Errors encountered trying to gather facts with the collection.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.asa.asa_facts

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = /home/username/Ansible-CiscoASA/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/username/Ansible-CiscoASA/ansible.cfg) = ['/home/username/.ansible/collections']
DEFAULT_HOST_LIST(/home/username/Ansible-CiscoASA/ansible.cfg) = ['/home/username/Ansible-CiscoASA/production']
HOST_KEY_CHECKING(/home/username/Ansible-CiscoASA/ansible.cfg) = False
INTERPRETER_PYTHON(/home/username/Ansible-CiscoASA/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/home/username/Ansible-CiscoASA/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ansible host: Ubuntu 18.04.2 LTS
ASA: 9.10(1)30

##### STEPS TO REPRODUCE

ansible-playbook test_rule_new.yml -u username --ask-pass --ask-become-pass -vvvv

```yaml
---
#this builds a sample rule in VRF32 - it looks to see if this EXACT line exists in the ACL list, and creates it if it does not
- hosts: asa
  tasks:
  - name: Gather all legacy facts
    become: yes
    cisco.asa.asa_facts:
      gather_subset:
      - config
```

##### EXPECTED RESULTS

Return facts successfully.

##### ACTUAL RESULTS

(Replaced sensitive values)
```paste below
ansible-playbook test_rule_new.yml -u username --ask-pass --ask-become-pass -vvvv
ansible-playbook 2.9.5
  config file = /home/username/Ansible-CiscoASA/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Using /home/username/Ansible-CiscoASA/ansible.cfg as config file
SSH password: 
BECOME password[defaults to SSH password]: 
setting up inventory plugins
host_list declined parsing /home/username/Ansible-CiscoASA/production as it did not pass its verify_file() method
script declined parsing /home/username/Ansible-CiscoASA/production as it did not pass its verify_file() method
auto declined parsing /home/username/Ansible-CiscoASA/production as it did not pass its verify_file() method
Parsed /home/username/Ansible-CiscoASA/production inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.6/dist-packages/ansible/plugins/callback/default.py

PLAYBOOK: test_rule_new.yml *************************************************************************************************************************
Positional arguments: test_rule_new.yml
verbosity: 4
ask_pass: True
remote_user: username
connection: smart
timeout: 10
become_method: sudo
become_ask_pass: True
tags: ('all',)
inventory: ('/home/username/Ansible-CiscoASA/production',)
forks: 5
1 plays in test_rule_new.yml

PLAY [asa] ******************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************
task path: /home/username/Ansible-CiscoASA/test_rule_new.yml:3
<10.10.10.10> attempting to start connection
<10.10.10.10> using connection plugin network_cli
<10.10.10.10> local domain socket does not exist, starting it
<10.10.10.10> control socket path is /home/username/.ansible/pc/357ccb133a
<10.10.10.10> local domain socket listeners started successfully
<10.10.10.10> loaded cliconf plugin asa from path /usr/local/lib/python3.6/dist-packages/ansible/plugins/cliconf/asa.py for network_os asa
<10.10.10.10> 
<10.10.10.10> local domain socket path is /home/username/.ansible/pc/357ccb133a
<10.10.10.10> ESTABLISH LOCAL CONNECTION FOR USER: username
<10.10.10.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484924.2645752-268035200652713 `" && echo ansible-tmp-1593484924.2645752-268035200652713="` echo /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484924.2645752-268035200652713 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/dist-packages/ansible/modules/system/setup.py
<10.10.10.10> PUT /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/tmphixothel TO /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484924.2645752-268035200652713/AnsiballZ_setup.py
<10.10.10.10> EXEC /bin/sh -c 'chmod u+x /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484924.2645752-268035200652713/ /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484924.2645752-268035200652713/AnsiballZ_setup.py && sleep 0'
<10.10.10.10> EXEC /bin/sh -c '/usr/bin/python3 /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484924.2645752-268035200652713/AnsiballZ_setup.py && sleep 0'
<10.10.10.10> EXEC /bin/sh -c 'rm -f -r /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484924.2645752-268035200652713/ > /dev/null 2>&1 && sleep 0'
ok: [10.10.10.10]
META: ran handlers

TASK [Gather all legacy facts] **********************************************************************************************************************
task path: /home/username/Ansible-CiscoASA/test_rule_new.yml:5
<10.10.10.10> attempting to start connection
<10.10.10.10> using connection plugin network_cli
<10.10.10.10> found existing local domain socket, using it!
<10.10.10.10> updating play_context for connection
<10.10.10.10> ssh connection done, setting terminal
<10.10.10.10> loaded terminal plugin for network_os asa
<10.10.10.10> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<10.10.10.10> firing event: on_open_shell()
<10.10.10.10> ssh connection has completed successfully
<10.10.10.10> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<10.10.10.10> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<10.10.10.10> authorizing connection
<10.10.10.10> 
<10.10.10.10> local domain socket path is /home/username/.ansible/pc/357ccb133a
<10.10.10.10> ESTABLISH LOCAL CONNECTION FOR USER: username
<10.10.10.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478 `" && echo ansible-tmp-1593484927.7340422-65588891130478="` echo /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478 `" ) && sleep 0'
Using module file /home/username/.ansible/collections/ansible_collections/cisco/asa/plugins/modules/asa_facts.py
<10.10.10.10> PUT /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/tmp1w7dpkqc TO /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/AnsiballZ_asa_facts.py
<10.10.10.10> EXEC /bin/sh -c 'chmod u+x /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/ /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/AnsiballZ_asa_facts.py && sleep 0'
<10.10.10.10> EXEC /bin/sh -c '/usr/bin/python3 /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/AnsiballZ_asa_facts.py && sleep 0'
<10.10.10.10> EXEC /bin/sh -c 'rm -f -r /home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/AnsiballZ_asa_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/AnsiballZ_asa_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/AnsiballZ_asa_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.asa.plugins.modules.asa_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.asa.asa_facts_payload_ltlft16w/ansible_cisco.asa.asa_facts_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_facts.py", line 206, in <module>
  File "/tmp/ansible_cisco.asa.asa_facts_payload_ltlft16w/ansible_cisco.asa.asa_facts_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_facts.py", line 197, in main
  File "/tmp/ansible_cisco.asa.asa_facts_payload_ltlft16w/ansible_cisco.asa.asa_facts_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/facts.py", line 64, in get_facts
  File "/tmp/ansible_cisco.asa.asa_facts_payload_ltlft16w/ansible_cisco.asa.asa_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 153, in get_network_legacy_facts
  File "/tmp/ansible_cisco.asa.asa_facts_payload_ltlft16w/ansible_cisco.asa.asa_facts_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/legacy/base.py", line 53, in populate
TypeError: 'NoneType' object is not subscriptable
fatal: [10.10.10.10]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/AnsiballZ_asa_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/AnsiballZ_asa_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/username/.ansible/tmp/ansible-local-20434zhssd7kn/ansible-tmp-1593484927.7340422-65588891130478/AnsiballZ_asa_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.asa.plugins.modules.asa_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.asa.asa_facts_payload_ltlft16w/ansible_cisco.asa.asa_facts_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_facts.py\", line 206, in <module>\n  File \"/tmp/ansible_cisco.asa.asa_facts_payload_ltlft16w/ansible_cisco.asa.asa_facts_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_facts.py\", line 197, in main\n  File \"/tmp/ansible_cisco.asa.asa_facts_payload_ltlft16w/ansible_cisco.asa.asa_facts_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/facts.py\", line 64, in get_facts\n  File \"/tmp/ansible_cisco.asa.asa_facts_payload_ltlft16w/ansible_cisco.asa.asa_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 153, in get_network_legacy_facts\n  File \"/tmp/ansible_cisco.asa.asa_facts_payload_ltlft16w/ansible_cisco.asa.asa_facts_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/legacy/base.py\", line 53, in populate\nTypeError: 'NoneType' object is not subscriptable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ******************************************************************************************************************************************
10.10.10.10                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by justjais** [comment] 2020-07-07 07:11
@rayterrill can u plz share the output of `show version` from your ASA device, as I have tested the scenario in ASA 9.12(3) and it's working as expected for me.

**Comment by rayterrill** [comment] 2020-07-07 17:21
```
Cisco Adaptive Security Appliance Software Version 9.10(1)30 <context>
Firepower Extensible Operating System Version 2.6(1.156)
Device Manager Version 7.13(1)

Compiled on Tue 10-Sep-19 09:18 PDT by builders

PDXASA up 244 days 7 hours
failover cluster up 247 days 23 hours

SSP Slot Number: 1  

Hardware:   FPR4K-SM-36, 230649 MB RAM, CPU Xeon E5 series 2300 MHz, 2 CPUs (72 cores)

Encryption hardware device : Cisco FP Crypto on-board accelerator (revision 0x1)
                             Boot microcode        : CN35x-MC-Boot-0001
                             SSL/IKE microcode     : CNN35x-MC-SSL-0014
                             IPSec microcode       : CNN35x-MC-IPSEC-0005
                             Number of accelerators: 2

4099: Int: Internal-Data0/0    : address is 0015.a500.01bf, irq 11
4101: Int: Internal-Data0/1    : address is 0015.a500.01ff, irq 5
4102: Int: Internal-Data0/2    : address is a201.0000.0002, irq 0
4103: Int: Internal-Data0/3    : address is 0000.0001.0003, irq 0

License mode: Smart Licensing

Licensed features for this platform:
Maximum Physical Interfaces       : Unlimited      
Maximum VLANs                     : 1024           
Inside Hosts                      : Unlimited      
Failover                          : Active/Active  
Encryption-DES                    : Enabled        
Encryption-3DES-AES               : Enabled        
Security Contexts                 : 90             
Carrier                           : Disabled       
AnyConnect Premium Peers          : 20000          
AnyConnect Essentials             : Disabled       
Other VPN Peers                   : 20000          
Total VPN Peers                   : 20000          
AnyConnect for Mobile             : Enabled        
AnyConnect for Cisco VPN Phone    : Enabled        
Advanced Endpoint Assessment      : Enabled        
Shared License                    : Disabled       
Total TLS Proxy Sessions          : 15000          
Cluster                           : Enabled        


Failover cluster licensed features for this platform:
Maximum Physical Interfaces       : Unlimited      
Maximum VLANs                     : 1024           
Inside Hosts                      : Unlimited      
Failover                          : Active/Active  
Encryption-DES                    : Enabled        
Encryption-3DES-AES               : Enabled        
Security Contexts                 : 100            
Carrier                           : Disabled       
AnyConnect Premium Peers          : 20000          
AnyConnect Essentials             : Disabled       
Other VPN Peers                   : 20000          
Total VPN Peers                   : 20000          
AnyConnect for Mobile             : Enabled        
AnyConnect for Cisco VPN Phone    : Enabled        
Advanced Endpoint Assessment      : Enabled        
Shared License                    : Disabled       
Total TLS Proxy Sessions          : 15000          
Cluster                           : Enabled        


Serial Number: FLM2150002M
Configuration last modified by user at 14:18:18.969 PDT Mon Jun 29 2020
```

**Comment by justjais** [comment] 2020-07-10 07:40
@rayterrill Thanks for pasting the output, can you please test the scenario again with Ansible `2.9.10` and verify if you're still seeing the issue.

**Comment by rayterrill** [comment] 2020-07-14 23:15
@justjais it did indeed work when upgraded to Ansible 2.9.10. Unfortunately that was just a test to get to asa_acls which is what I'm really after.

Updated my playbook to the following (stolen from https://www.ansible.com/blog/ansible-security-automation-resource-modules):
```
---
- hosts: asa
  gather_facts: false
  collections:
   - cisco.asa

  tasks:
  - name: Gather facts
    asa_acls:
      state: gathered
    register: gather
  - name: output data
    debug:
      vars: "{ gather }}"
```

That's failing with:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-local-23293igh_syau/ansible-tmp-1594768247.3244836-23300-246461498837720/AnsiballZ_asa_acls.py", line 102, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-local-23293igh_syau/ansible-tmp-1594768247.3244836-23300-246461498837720/AnsiballZ_asa_acls.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-local-23293igh_syau/ansible-tmp-1594768247.3244836-23300-246461498837720/AnsiballZ_asa_acls.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.asa.plugins.modules.asa_acls', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_acls.py", line 1238, in <module>
  File "/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_acls.py", line 1233, in main
  File "/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 88, in execute_module
  File "/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 54, in get_acls_facts
  File "/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/facts.py", line 59, in get_facts
  File "/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 128, in get_network_resources_facts
  File "/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/acls/acls.py", line 70, in populate_facts
  File "/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/acls/acls.py", line 457, in render_config
  File "/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/acls/acls.py", line 216, in populate_source_destination
ValueError: 'any' is not in list
fatal: [10.99.6.1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-local-23293igh_syau/ansible-tmp-1594768247.3244836-23300-246461498837720/AnsiballZ_asa_acls.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-local-23293igh_syau/ansible-tmp-1594768247.3244836-23300-246461498837720/AnsiballZ_asa_acls.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-local-23293igh_syau/ansible-tmp-1594768247.3244836-23300-246461498837720/AnsiballZ_asa_acls.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.asa.plugins.modules.asa_acls', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_acls.py\", line 1238, in <module>\n  File \"/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_acls.py\", line 1233, in main\n  File \"/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py\", line 88, in execute_module\n  File \"/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py\", line 54, in get_acls_facts\n  File \"/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/facts.py\", line 59, in get_facts\n  File \"/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 128, in get_network_resources_facts\n  File \"/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/acls/acls.py\", line 70, in populate_facts\n  File \"/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/acls/acls.py\", line 457, in render_config\n  File \"/tmp/ansible_asa_acls_payload_xxsgr3_x/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/acls/acls.py\", line 216, in populate_source_destination\nValueError: 'any' is not in list\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by justjais** [comment] 2020-07-15 12:42
@rayterrill Thanks for the update, and there's already an issue open wrt to the observed behavior, plz ref: https://github.com/ansible-collections/cisco.asa/issues/56.

I'll try to add the feature fix soon :)

**Comment by justjais** [comment] 2020-07-15 12:42
Closing the issue as it's duplicate of #56

**Closed by justjais** 2020-07-15 12:42 UTC

**Comment by rayterrill** [comment] 2020-07-15 16:35
@justjais thank you sir!
