### ISSUE TITLE
Help wanted!

### ISSUE THREAD

**Issue by yuandongx** [ansible-collections/cisco.asa#83] opened 2021-01-12 09:22 UTC
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

asa_config.py
##### ANSIBLE VERSION

```paste below
ansible-2.9.7
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ubuntu 20

##### STEPS TO REPRODUCE

When I run a command `access-list test-acl-1 extended permit tcp object-group IP_Test host 10.22.5.38 eq 8080` and `IP_Test` does not exist on my device, and then an error should happend, but not.
The error msg is more than 256 chars with CLI, but ansible tells me task is successful.
May link to ansible-collections/ansible.netcommon#201.

```yaml

```

##### EXPECTED RESULTS

ansible reports `update`

##### ACTUAL RESULTS

```paste below
ansible reports `error`
```

**Comment by yuandongx** [comment] 2021-01-12 09:27
I think the error message is more than 256 and Ansible will not wor will. The reason is that `network_cli` can not deal with much long error message. [Code](https://github.com/ansible-collections/ansible.netcommon/blob/486a01bae9e46b92d9829d2d571e78121965ade4/plugins/connection/network_cli.py#L1014)  wotks not well.

**Comment by yuandongx** [comment] 2021-01-12 09:51
### `access-list test-acl-1 extended permit tcp object-group IP_Test host 10.22.5.38 eq 8080` CLI output
```
ERROR: specified object group <IP_Test> not found
Usage:
Extended access list:
        Use this to configure policy for IP traffic through the firewall

[no] access-list <id> [line <line_num>] [extended] {deny | permit}
                {<protocol> | object-group {<service_obj_grp_id> |
                <protocol_obj_grp_id>}}
                {host <sip> | <sip> <smask> | interface <ifc> | any |
                object-group <network_obj_grp_id>}
                [<operator> <port> [<port>] |
                object-group <service_obj_grp_id>]
                {host <dip> | <dip> <dmask> | interface <ifc> | any |
                object-group <network_obj_grp_id>}
                [<operator> <port> [<port>] |
                object-group <service_obj_grp_id>]
                [log [disable] | [<level>] | [default] [interval <secs>]]
[no] access-list <id> [line <line_num>] {deny | permit} icmp
                {host <sip> | <sip> <smask> |
                object-group <network_obj_grp_id>}
                {<dip> <dmask> | object-group <network_obj_grp_id>}
                [<icmp_type> | object-group <icmp_type_obj_grp_id>]
                [log [disable] | [<level>] | [default] [interval <secs>]]
[no] access-list <id> webtype {deny|permit}
                url {<url-string>|any} [log {disable | default | level}
                [interval <seconds>]] [time-range <name>] [inactive]
[no] access-list <id> webtype {deny | permit>
                tcp {host <host-addr> | <dest-addr> <dest-mask> | any}
                [{{EQ | NEQ | LT | GT} <port> | RANGE <port> <port>}]
                [log {disable | default | <level>} [interval <seconds>]]
                [time-range <name> ] [ inactive ]
[no] access-list <id> [line <line_num>] remark <text>
access-list deny-flow-max <n>
access-list alert-interval <secs>

Standard access list:
        Use this to configure policy having destination host or network only

[no] access-list <id> standard {deny|permit} {any | <ip> <mask> | host <ip>}
[no] access-list <id> remark <text>

Generic Commands:

access-lsit <id> rename <new_id>
show access-list [<id>]
show running-config access-list
                [alert-interval | deny-flow-max | <id>]
clear configure access-list [<id>]
clear access-list [<id> [counters]]

```

**Comment by Qalthos** [comment] 2021-01-12 22:40
This is also a duplicate of ansible-collections/ansible.netcommon#16.

**Closed by Qalthos** 2021-01-12 22:40 UTC
